/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author menes
 */
public class HesapMak extends javax.swing.JFrame {

    /**
     * Creates new form HesapMak
     */
    public HesapMak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTopla = new javax.swing.JButton();
        btnCikar = new javax.swing.JButton();
        btnCarp = new javax.swing.JButton();
        btnBol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBirinci = new javax.swing.JTextField();
        txtİkinci = new javax.swing.JTextField();
        txtSonuc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTopla.setText("+");
        btnTopla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplaActionPerformed(evt);
            }
        });

        btnCikar.setText("-");
        btnCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikarActionPerformed(evt);
            }
        });

        btnCarp.setText("x");
        btnCarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpActionPerformed(evt);
            }
        });

        btnBol.setText("/");
        btnBol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolActionPerformed(evt);
            }
        });

        jLabel1.setText("Birinci Sayı :");

        jLabel2.setText("İkinci Sayı :");

        jLabel3.setText("Sonuç :");

        txtİkinci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtİkinciActionPerformed(evt);
            }
        });

        txtSonuc.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTopla)
                            .addComponent(btnCarp))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBol)
                            .addComponent(btnCikar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtBirinci))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(txtİkinci, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtSonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBirinci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtİkinci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTopla)
                            .addComponent(btnCikar))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCarp)
                            .addComponent(btnBol))
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSonuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtİkinciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtİkinciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtİkinciActionPerformed

    private void btnToplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplaActionPerformed
        int birinciSayi = Integer.valueOf(this.txtBirinci.getText()); // txtBirinci'den gelen değer string olacağı için onu int değere çevridik.
        int ikinciSayi = Integer.valueOf(this.txtİkinci.getText());
        txtSonuc.setText(String.valueOf(birinciSayi+ikinciSayi)); // gelecek sonuc değeri integer olacağı için bunu da stringe çevirmemiz gerektiğinden stringvalueof kullandık.
    }//GEN-LAST:event_btnToplaActionPerformed

    private void btnCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikarActionPerformed
int birinciSayi = Integer.valueOf(this.txtBirinci.getText()); // txtBirinci'den gelen değer string olacağı için onu int değere çevridik.
        int ikinciSayi = Integer.valueOf(this.txtİkinci.getText());
        txtSonuc.setText(String.valueOf(birinciSayi-ikinciSayi)); // gelecek sonuc değeri integer olacağı için bunu da stringe çevirmemiz gerektiğinden stringvalueof kullandık.
    }//GEN-LAST:event_btnCikarActionPerformed

    private void btnCarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarpActionPerformed
int birinciSayi = Integer.valueOf(this.txtBirinci.getText()); // txtBirinci'den gelen değer string olacağı için onu int değere çevridik.
        int ikinciSayi = Integer.valueOf(this.txtİkinci.getText());
        txtSonuc.setText(String.valueOf(birinciSayi*ikinciSayi)); // gelecek sonuc değeri integer olacağı için bunu da stringe çevirmemiz gerektiğinden stringvalueof kullandık.        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarpActionPerformed

    private void btnBolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolActionPerformed
int birinciSayi = Integer.valueOf(this.txtBirinci.getText()); // txtBirinci'den gelen değer string olacağı için onu int değere çevridik.
        int ikinciSayi = Integer.valueOf(this.txtİkinci.getText());
        txtSonuc.setText(String.valueOf(birinciSayi/ikinciSayi)); // gelecek sonuc değeri integer olacağı için bunu da stringe çevirmemiz gerektiğinden stringvalueof kullandık.        // TODO add your handling code here:
    }//GEN-LAST:event_btnBolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapMak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapMak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapMak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapMak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HesapMak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBol;
    private javax.swing.JButton btnCarp;
    private javax.swing.JButton btnCikar;
    private javax.swing.JButton btnTopla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtBirinci;
    private javax.swing.JTextField txtSonuc;
    private javax.swing.JTextField txtİkinci;
    // End of variables declaration//GEN-END:variables
}
